name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Gradle Cache
      uses: burrunan/gradle-cache-action@v1
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      
    - name: Install dependencies
      run: npm ci && npm install -g @ionic/cli native-run cordova-res

    - name: Ionic build
      run: ionic build
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      
    - name: Build with Gradle
      run: ./gradlew android/app/build
      
    - name: Show build
      run: ls android/app/build/outputs/apk
