name: Android CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0
      
    - name: Install dependencies
      run: npm ci && npm install -g @ionic/cli native-run cordova-res

    - name: Ionic build
      run: ionic build
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.3.0

      
    - name: Gradle Build Action
      uses: gradle/gradle-build-action@v2.2.0
      with:
        build-root-directory: android
      
    - name: Show build
      run: ls android/app/build/outputs/apk
